In [7]:
from numpy.linalg import det,inv
from numpy import array,matrix

In [10]:
#mat_a=matrix([[-2,3,-1],[1,2,-1],[-2,-1,1]])
mat_a=array([[-2,3,-1],[1,2,-1],[-2,-1,1]])

In [11]:
det(mat_a)

-1.9999999999999998

In [12]:
inv(mat_a)

array([[-0.5,  1. ,  0.5],
       [-0.5,  2. ,  1.5],
       [-1.5,  4. ,  3.5]])

In [14]:
cof_matrix=array([[-2,3,-1],[1,2,-1],[-2,-1,1]])
#y=array([[1],[4],[-3]])
y=array([[1,4,-3]])

In [16]:
y.shape

(1, 3)

In [17]:
y.reshape(3,1)

array([[ 1],
       [ 4],
       [-3]])

In [18]:
#Transpose y
y.T

array([[ 1],
       [ 4],
       [-3]])

In [19]:
inv(cof_matrix)@y.T

array([[2.],
       [3.],
       [4.]])