In [12]:
from numpy import random
import pandas as pd


Generating random numbers from distributions

In [5]:
random.binomial(3,0.5,10)


array([2, 3, 2, 2, 1, 1, 2, 1, 1, 1])

Observation (when using binomial)
This is because the probability of getting 1 and 2 is higher than getting a 0 and 3








In [6]:
random.binomial(100,0.5,10)

array([60, 57, 47, 46, 61, 45, 42, 49, 48, 45])

Poisson

In [9]:
random.poisson(2,15)

array([1, 0, 2, 2, 2, 3, 1, 4, 1, 0, 2, 5, 3, 1, 3])

Uniform lowest-0 highest 1

20 values which are uniformly distributed

In [10]:
random.uniform(0,1,20)

array([0.56576455, 0.33943817, 0.06051976, 0.15404051, 0.46352171,
       0.43488036, 0.95884368, 0.22295518, 0.06829754, 0.3508051 ,
       0.10576819, 0.96235722, 0.32182115, 0.57526223, 0.30047762,
       0.11195957, 0.50836744, 0.00138093, 0.18263297, 0.58180147])

Normal(mean,variance,no. of output)

In [15]:
dummy_data={'Age':random.normal(33,1,15),'Gender':random.binomial(1,0.5,15),'Location':random.poisson(2,15),'Income':random.uniform(30,10,15)}

In [16]:
pd.DataFrame(dummy_data)

Age  Gender  Location     Income
0   32.691729       0         4  11.733514
1   32.246078       0         3  21.383345
2   33.591877       1         4  26.384696
3   32.528648       0         2  10.849483
4   32.938237       1         0  17.009310
5   34.196896       0         2  18.707193
6   33.913979       1         1  13.336208
7   32.418739       0         0  12.199511
8   34.221736       0         3  11.072848
9   32.525055       1         1  23.289218
10  34.369370       0         4  27.428687
11  32.409071       0         1  16.507532
12  32.240590       1         0  16.268482
13  33.373993       1         3  12.476005
14  33.673107       1         5  12.704193