In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import sklearn.linear_model

Step 1:Grab the dataset



> Search for missing values



In [ ]:
data=pd.read_csv('/content/modified_data.csv')

In [ ]:
data.head()

Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 77 columns]

Step Two:Prepare Dataset

In [ ]:
data.drop('Id',axis=1,inplace=True)

In [ ]:
data.head()

MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
0          60       RL         65.0  ...        WD        Normal    208500
1          20       RL         80.0  ...        WD        Normal    181500
2          60       RL         68.0  ...        WD        Normal    223500
3          70       RL         60.0  ...        WD       Abnorml    140000
4          60       RL         84.0  ...        WD        Normal    250000

[5 rows x 76 columns]

In [ ]:
data.shape

(1460, 76)

In [ ]:
data.isna().any()

MSSubClass       False
MSZoning         False
LotFrontage       True
LotArea          False
Street           False
                 ...  
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice        False
Length: 76, dtype: bool

In [ ]:
#Get all col
data.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF'

In [ ]:
original_features=list(data.columns)
original_features

['MSSubClass',
 'MSZoning',
 'LotFrontage',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'MasVnrArea',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinSF1',
 'BsmtFinType2',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'KitchenQual',
 'TotRmsAbvGrd',
 'Functional',
 'Fireplaces',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageCars',
 'GarageArea',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch

In [ ]:
features_with_missing=list(data.columns[data.isna().any()])
features_with_missing
len(features_with_missing)

15

In [ ]:
len(data)

1460

In [ ]:
for feature in features_with_missing:
  print(feature,'',(data[feature].isna().sum())/len(data)*100)

LotFrontage  17.73972602739726
MasVnrType  0.547945205479452
MasVnrArea  0.547945205479452
BsmtQual  2.5342465753424657
BsmtCond  2.5342465753424657
BsmtExposure  2.6027397260273974
BsmtFinType1  2.5342465753424657
BsmtFinType2  2.6027397260273974
Electrical  0.0684931506849315
FireplaceQu  47.26027397260274
GarageType  5.5479452054794525
GarageYrBlt  5.5479452054794525
GarageFinish  5.5479452054794525
GarageQual  5.5479452054794525
GarageCond  5.5479452054794525


In [ ]:
#Axis 0=row,axis 1=column (0,4 threshhold-drop values with 40% and above missing will be dropped)
data.dropna(axis=1,thresh=0.5*(len(data)),inplace=True)

In [ ]:
mean_fill=['LotFrontage','MasVnrArea']
bfill=['FireplaceQu']
ffill=list(set(features_with_missing)-set(mean_fill)-set(bfill))

In [ ]:
ffill

['BsmtFinType1',
 'BsmtExposure',
 'MasVnrType',
 'Electrical',
 'GarageYrBlt',
 'GarageFinish',
 'GarageType',
 'GarageQual',
 'BsmtCond',
 'BsmtFinType2',
 'GarageCond',
 'BsmtQual']

In [ ]:
for feature in mean_fill:
  data[feature].fillna(data[feature].mean(),inplace=True)

In [ ]:
for feature in ffill:
  data[feature].fillna(method='ffill',inplace=True)

In [ ]:
for feature in bfill:
  data[feature].fillna(method='bfill',inplace=True)

In [ ]:
data.isna().any()

MSSubClass       False
MSZoning         False
LotFrontage      False
LotArea          False
Street           False
                 ...  
MoSold           False
YrSold           False
SaleType         False
SaleCondition    False
SalePrice        False
Length: 76, dtype: bool



> Encode the dataset



In [ ]:
cat_data=data.select_dtypes(include=['object']).copy()
cat_data.head(2)

MSZoning Street LotShape  ... PavedDrive SaleType SaleCondition
0       RL   Pave      Reg  ...          Y       WD        Normal
1       RL   Pave      Reg  ...          Y       WD        Normal

[2 rows x 39 columns]

In [ ]:
cat_features=list(cat_data.columns)
cat_features

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [ ]:
nominal=['MSZoning','LandContour','LotConfig','Neighborhood']
ordinal=list(set(cat_features)-set(nominal))
numerical=list(set(original_features)-set(cat_features))
target=['SalePrice']

In [ ]:
data[target]

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [ ]:
for feature in ordinal:
  data[feature]=(data[feature].astype('category')).cat.codes

In [ ]:
data[ordinal]

SaleCondition  Heating  Street  ...  SaleType  LandSlope  PavedDrive
0                 4        1       1  ...         8          0           2
1                 4        1       1  ...         8          0           2
2                 4        1       1  ...         8          0           2
3                 0        1       1  ...         8          0           2
4                 4        1       1  ...         8          0           2
...             ...      ...     ...  ...       ...        ...         ...
1455              4        1       1  ...         8          0           2
1456              4        1       1  ...         8          0           2
1457              4        1       1  ...         8          0           2
1458              4        1       1  ...         8          0           2
1459              4        1       1  ...         8          0           2

[1460 rows x 35 columns]

In [ ]:
#One hot encoding
df_nominal=pd.get_dummies(data[nominal])

In [ ]:
df_ordinal=data[ordinal]

In [ ]:
df_numerical=data[numerical]


> Create a new dataset



In [ ]:
encoded_data=pd.concat([df_numerical,df_nominal,df_ordinal],axis=1)

In [ ]:
encoded_data.head(3)

WoodDeckSF  MoSold  BedroomAbvGr  ...  SaleType  LandSlope  PavedDrive
0           0       2             3  ...         8          0           2
1         298       5             3  ...         8          0           2
2           0       9             3  ...         8          0           2

[3 rows x 111 columns]

In [ ]:
encoded_data.shape

(1460, 111)

Data Normalization

In [ ]:
encoded_data[target]

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [ ]:
X=encoded_data.drop('SalePrice',axis=1)

In [ ]:
X

WoodDeckSF  MoSold  BedroomAbvGr  ...  SaleType  LandSlope  PavedDrive
0              0       2             3  ...         8          0           2
1            298       5             3  ...         8          0           2
2              0       9             3  ...         8          0           2
3              0       2             3  ...         8          0           2
4            192      12             4  ...         8          0           2
...          ...     ...           ...  ...       ...        ...         ...
1455           0       8             3  ...         8          0           2
1456         349       2             3  ...         8          0           2
1457           0       5             4  ...         8          0           2
1458         366       4             2  ...         8          0           2
1459         736       6             3  ...         8          0           2

[1460 rows x 110 columns]

In [ ]:
y=data[target]
y

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [ ]:
# All datasets will become a matrix
X=X.to_numpy()
X

array([[  0.,   2.,   3., ...,   8.,   0.,   2.],
       [298.,   5.,   3., ...,   8.,   0.,   2.],
       [  0.,   9.,   3., ...,   8.,   0.,   2.],
       ...,
       [  0.,   5.,   4., ...,   8.,   0.,   2.],
       [366.,   4.,   2., ...,   8.,   0.,   2.],
       [736.,   6.,   3., ...,   8.,   0.,   2.]])

In [ ]:
y=y.to_numpy()
y

array([[208500],
       [181500],
       [223500],
       ...,
       [266500],
       [142125],
       [147500]])

In [ ]:
X.shape

(1460, 110)

In [ ]:
y.shape

(1460, 1)

In [ ]:
X=StandardScaler().fit_transform(X)
y=StandardScaler().fit_transform(y)

In [ ]:
y

array([[ 0.34727322],
       [ 0.00728832],
       [ 0.53615372],
       ...,
       [ 1.07761115],
       [-0.48852299],
       [-0.42084081]])

In [ ]:
X.shape

(1460, 110)

PCA Dimensionality Reduction

In [ ]:
pca=PCA(n_components=2)
p_components=pca.fit_transform(X)

In [ ]:
p_components

array([[ 2.40853487, -1.3304114 ],
       [ 0.43196109,  2.62314865],
       [ 2.82844318, -0.85553068],
       ...,
       [ 1.25987909, -0.86311838],
       [-2.83066434,  3.18197186],
       [-0.75664659,  2.68263272]])

In [ ]:
pca.explained_variance_ratio_

array([0.10207313, 0.04345606])

In [ ]:
pca_var=PCA(0.9)
new_pcs=pca_var.fit_transform(X)

In [ ]:
pca_var.n_components_

70

In [ ]:
pca.explained_variance_ratio_

array([0.10207313, 0.04345606])

In [ ]:
p_components=pd.DataFrame(p_components,columns=['PC1','PC2'])

In [ ]:
y=pd.DataFrame(y,columns=['y'])

In [ ]:
new_data=pd.concat([p_components,y],axis=1)

In [ ]:
new_data

PC1       PC2         y
0     2.408535 -1.330411  0.347273
1     0.431961  2.623149  0.007288
2     2.828443 -0.855531  0.536154
3    -1.364218  0.550650 -0.515281
4     5.311988 -0.223575  0.869843
...        ...       ...       ...
1455  1.306602 -2.289615 -0.074560
1456  1.095834  3.178839  0.366161
1457  1.259879 -0.863118  1.077611
1458 -2.830664  3.181972 -0.488523
1459 -0.756647  2.682633 -0.420841

[1460 rows x 3 columns]